CREATE DATABASE marketmargodb;

USE marketmargodb;

CREATE TABLE tbusuario (
    Id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Senha VARCHAR(100) NOT NULL,
    Funcao INT NOT NULL,
    Data_Criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Data_Modificacao DATETIME,
    Ativo BIT NOT NULL DEFAULT b'1',
    Token VARCHAR(100)
);

CREATE TABLE tbproduto (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    setor VARCHAR(100) NOT NULL,
    id_categoria INT NOT NULL,
    quantidade INT NOT NULL,
    data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_modificacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ativo BIT NOT NULL DEFAULT b'1'
);

CREATE TABLE tbpreco (
    id INT AUTO_INCREMENT PRIMARY KEY,
    idProduto INT NOT NULL,
    porcentagemAumento DOUBLE NOT NULL,
    valor DOUBLE NOT NULL,
    data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_modificacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ativo BIT NOT NULL DEFAULT b'1'
);

CREATE TABLE tbcategoria (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_modificacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ativo BIT NOT NULL DEFAULT b'1'
);

CREATE TABLE tbgondola (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    categoria INT NOT NULL,
    id_categoria INT NOT NULL,
    data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_modificacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ativo BIT NOT NULL DEFAULT b'1'
);

CREATE TABLE tbcaixa (
    id INT AUTO_INCREMENT PRIMARY KEY,
    id_produto INT NOT NULL,
    quantidade INT NOT NULL,
    status INT NOT NULL,
    cod_barras VARCHAR(100),
    transacao_code VARCHAR(100),
    preco_produto DOUBLE NOT NULL,
    data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_modificacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ativo BIT NOT NULL DEFAULT b'1'
);



